/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorPuntos;
import Controladores.ControladorDevolCliente;
import Modelos.RegistroCompra;
import Modelos.Devolucion;
import Modelos.Usuarios.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VistaGestionCliente extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionCliente
     */
    Cliente cliente;
    ControladorPuntos cp;
    ControladorDevolCliente cdc;

    public VistaGestionCliente(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(this);
        
        this.cliente = cliente;
        cp = new ControladorPuntos(cliente);
        cdc = new ControladorDevolCliente(cliente);
        
        mostrarInfo();
        llenarTablaPuntos();
        llenarTablaDevoluciones();
    }
    
    // METODOS PRIVADOS DEL TAB DE INFO DE CLIENTE
    private void mostrarInfo() {
        nombreCliLabel.setText(cliente.getName());
        nroIdLabel.setText(cliente.getNroId() + "");
        emailLabel.setText(cliente.getEmail());
        telefonoLabel.setText(cliente.getTelefono());
        puntosAcumuladosLabel.setText(cliente.getPuntosAcumulados() + "");
        dineroInvertidoLabel.setText("$" + cliente.getDineroInvertido() + "");
    }
    // MÉTODOS PRIVADOS DEL TAB DE PUNTOS
    private void llenarTablaPuntos() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Puntos", "Viaje", "Bus","Empresa","Vlr Unit", "Cantidad Tiq","Fecha"});
        for (int i = 0; i < cp.getRegistroPuntos().size(); i++) {
            RegistroCompra regPunto = cp.getRegistroPuntos().get(i);
            int vlrUnit = regPunto.getViaje().getVlrUnit();
            model.addRow(new Object[]{
                regPunto.getPuntos(),
                regPunto.getViaje().getDestino() + " el " + regPunto.getViaje().getFechaSalidaStr(),
                regPunto.getViaje().getBus().getPlaca(),
                cp.getNombreEmpresaSegunViaje(regPunto.getViaje().getId()),
                vlrUnit,
                regPunto.getCantidadTiq(), // Formula para saber la cantidad de esa venta
                regPunto.getFechaCreacionStr(),
            });
        }
        puntosGanadosTable.setModel(model);
    }
    // MÉTODOS PRIVADOS DEL TAB DE DEVOLUCIONES
    private void llenarTablaDevoluciones() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID Tiquete", "Viaje", "Bus","Empresa","Vlr Unit","Fecha", "Resultado Puntos"});
        for (int i = 0; i < cdc.getDevoluciones().size(); i++) {
            Devolucion devolucion = cdc.getDevoluciones().get(i);
            model.addRow(new Object[]{
                devolucion.getTiquete().getId(),
                devolucion.getTiquete().getViaje().getDestino() + " el " + devolucion.getTiquete().getViaje().getFechaSalidaStr(),
                devolucion.getTiquete().getViaje().getBus().getPlaca(),
                cp.getNombreEmpresaSegunViaje(devolucion.getTiquete().getViaje().getId()),
                devolucion.getTiquete().getViaje().getVlrUnit(),
                devolucion.getFechaDevolucion(),
                devolucion.getResultadoPuntos()
            });
        }
        tablaDevoluciones1.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteTabbedPane = new javax.swing.JTabbedPane();
        informacionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombreCliLabel = new javax.swing.JLabel();
        nroIdLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        puntosAcumuladosLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dineroInvertidoLabel = new javax.swing.JLabel();
        puntosAcumulados = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        puntosGanadosTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        puntosRedimidosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPuntosRedimidos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        devolucionesPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDevoluciones1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        reservarTiqPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        notificacionesPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        cerrarSesionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Numero de Identificacion:");

        jLabel8.setText("Email:");

        jLabel9.setText("Telefono:");

        nombreCliLabel.setText("jLabel10");

        nroIdLabel.setText("jLabel11");

        emailLabel.setText("jLabel12");

        telefonoLabel.setText("jLabel13");

        jLabel10.setText("Puntos Acumulados");

        puntosAcumuladosLabel.setText("jLabel13");

        jLabel12.setText("Dinero Invertido");

        dineroInvertidoLabel.setText("jLabel13");

        javax.swing.GroupLayout informacionPanelLayout = new javax.swing.GroupLayout(informacionPanel);
        informacionPanel.setLayout(informacionPanelLayout);
        informacionPanelLayout.setHorizontalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(46, 46, 46)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dineroInvertidoLabel)
                    .addComponent(puntosAcumuladosLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(emailLabel)
                    .addComponent(nroIdLabel)
                    .addComponent(nombreCliLabel))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        informacionPanelLayout.setVerticalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreCliLabel))
                .addGap(30, 30, 30)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nroIdLabel))
                .addGap(33, 33, 33)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emailLabel))
                .addGap(37, 37, 37)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(telefonoLabel))
                .addGap(34, 34, 34)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(puntosAcumuladosLabel))
                .addGap(36, 36, 36)
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dineroInvertidoLabel))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Mi información", informacionPanel);

        puntosGanadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Puntos", "Viaje", "Fecha Salida", "Bus", "Empresa", "Fecha Creacion"
            }
        ));
        jScrollPane5.setViewportView(puntosGanadosTable);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Historial Puntos Ganados");

        javax.swing.GroupLayout puntosAcumuladosLayout = new javax.swing.GroupLayout(puntosAcumulados);
        puntosAcumulados.setLayout(puntosAcumuladosLayout);
        puntosAcumuladosLayout.setHorizontalGroup(
            puntosAcumuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puntosAcumuladosLayout.createSequentialGroup()
                .addGroup(puntosAcumuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puntosAcumuladosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puntosAcumuladosLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel11)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        puntosAcumuladosLayout.setVerticalGroup(
            puntosAcumuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puntosAcumuladosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Puntos Ganados", puntosAcumulados);

        tablaPuntosRedimidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tiquete", "Cliente", "Fecha Devolucion", "Monto Devuelto"
            }
        ));
        jScrollPane2.setViewportView(tablaPuntosRedimidos);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Historial Puntos Redimidos");

        javax.swing.GroupLayout puntosRedimidosPanelLayout = new javax.swing.GroupLayout(puntosRedimidosPanel);
        puntosRedimidosPanel.setLayout(puntosRedimidosPanelLayout);
        puntosRedimidosPanelLayout.setHorizontalGroup(
            puntosRedimidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puntosRedimidosPanelLayout.createSequentialGroup()
                .addGroup(puntosRedimidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puntosRedimidosPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puntosRedimidosPanelLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        puntosRedimidosPanelLayout.setVerticalGroup(
            puntosRedimidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puntosRedimidosPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        clienteTabbedPane.addTab("Puntos Redimidos", puntosRedimidosPanel);

        tablaDevoluciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tiquete", "Cliente", "Fecha Devolucion", "Monto Devuelto"
            }
        ));
        jScrollPane6.setViewportView(tablaDevoluciones1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Historial Devoluciones");

        javax.swing.GroupLayout devolucionesPanelLayout = new javax.swing.GroupLayout(devolucionesPanel);
        devolucionesPanel.setLayout(devolucionesPanelLayout);
        devolucionesPanelLayout.setHorizontalGroup(
            devolucionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devolucionesPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(devolucionesPanelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        devolucionesPanelLayout.setVerticalGroup(
            devolucionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucionesPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Devoluciones", devolucionesPanel);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mensaje", "Fecha envío"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout reservarTiqPanelLayout = new javax.swing.GroupLayout(reservarTiqPanel);
        reservarTiqPanel.setLayout(reservarTiqPanelLayout);
        reservarTiqPanelLayout.setHorizontalGroup(
            reservarTiqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservarTiqPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        reservarTiqPanelLayout.setVerticalGroup(
            reservarTiqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservarTiqPanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        clienteTabbedPane.addTab("Reservar", reservarTiqPanel);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mensaje", "Fecha envío"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        javax.swing.GroupLayout notificacionesPanelLayout = new javax.swing.GroupLayout(notificacionesPanel);
        notificacionesPanel.setLayout(notificacionesPanelLayout);
        notificacionesPanelLayout.setHorizontalGroup(
            notificacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificacionesPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        notificacionesPanelLayout.setVerticalGroup(
            notificacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificacionesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Notificaciones", notificacionesPanel);

        cerrarSesionBtn.setText("Cerrar Sesión");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteTabbedPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarSesionBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clienteTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarSesionBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        new VistaAccesoUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JTabbedPane clienteTabbedPane;
    private javax.swing.JPanel devolucionesPanel;
    private javax.swing.JLabel dineroInvertidoLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel informacionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel nombreCliLabel;
    private javax.swing.JPanel notificacionesPanel;
    private javax.swing.JLabel nroIdLabel;
    private javax.swing.JPanel puntosAcumulados;
    private javax.swing.JLabel puntosAcumuladosLabel;
    private javax.swing.JTable puntosGanadosTable;
    private javax.swing.JPanel puntosRedimidosPanel;
    private javax.swing.JPanel reservarTiqPanel;
    private javax.swing.JTable tablaDevoluciones1;
    private javax.swing.JTable tablaPuntosRedimidos;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration//GEN-END:variables
}
